name: Generate playlist.m3u

on:
  push:
    paths:
      - channels.json
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Generate playlist.m3u
        run: python generate_playlist.py

      - name: Commit and push
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add playlist.m3u
          git diff --cached --quiet && exit 0
          git commit -m "Auto update playlist.m3u"
          git push
